<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Pamac</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Pamac.Shared/Pamac.Shared.csproj" />
    <ProjectReference Include="../../bindings/LibAlpm/LibAlpm.csproj" />
  </ItemGroup>
</Project>
