<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>pamac-checkupdates</AssemblyName>
    <RootNamespace>Pamac</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Pamac/Pamac.csproj" />
    <ProjectReference Include="../Pamac.Shared/Pamac.Shared.csproj" />
    <ProjectReference Include="../../bindings/LibAlpm/LibAlpm.csproj" />
  </ItemGroup>
</Project>
